Repository yomidevs/yomitan, pull requests merged in 2023-08, with the labels that each got.

#209 Firefox fixes
  README.md
  dev/data/manifest-variants.json
  ext/js/background/backend.js
  ext/js/background/request-builder.js
  ext/js/background/script-manager.js
  ext/js/language/text-scanner.js
  ext/lib/handlebars.min.js.map
  ext/permissions.html
Labels: kind/bug, browser/firefox

#212 Fix caching and fonts in playwright.yml
  .github/workflows/playwright.yml
Labels: kind/meta

#213 Update README.md
  README.md
Labels: area/documentation, kind/meta

#214 Add Intuitive Permission Toggle to Welcome Page
  ext/js/pages/settings/recommended-permissions-controller.js
  ext/js/pages/welcome-main.js
  ext/welcome.html
Labels: kind/enhancement, area/ui-ux

#218 Attempt to fix auto-approval CI workflow
  .github/workflows/auto-approve-run.yml
  .github/workflows/auto-approve.yml
Labels: kind/meta

#217 Create CODEOWNERS
  CODEOWNERS
Labels: kind/meta
