Repository yomidevs/yomitan, pull requests merged in 2023-10, with the labels that each got.

#264 Update tough-cookie dependency
  package-lock.json
Labels: area/dependencies

#259 Fix Chrome death, by creating both cross-frame ports in the background
  ext/js/background/backend.js
  ext/js/comm/api.js
  ext/js/comm/cross-frame-api.js
  ext/js/yomichan.js
Labels: kind/bug, priority/high

#265 fix: page and popup state is destroyed on background wakeup
  ext/js/yomichan.js
Labels: kind/bug

#279 Edit `vertical-align` style for structured content hyperlinks
  ext/css/structured-content.css
Labels: kind/bug

#278 Fix chromium clipboard access
  dev/data/manifest-variants.json
  docs/permissions.md
  ext/js/background/backend.js
  ext/js/background/offscreen-main.js
  ext/js/background/offscreen.js
  ext/js/display/search-display-controller.js
  ext/offscreen.html
Labels: kind/bug

#281 Bump minimum Firefox version to 115 for storage.session support
  dev/data/manifest-variants.json
Labels: kind/bug, browser/firefox

#280 Create SECURITY.md
  SECURITY.md
Labels: kind/meta

#283 restore webRequestBlocking on Firefox
  dev/data/manifest-variants.json
  docs/permissions.md
Labels: kind/bug, browser/firefox

#284 save options after updating them
  ext/js/data/options-util.js
Labels: kind/bug
