Repository yomidevs/yomitan, pull requests merged in 2023-03, with the labels that each got.

#89 Use `lychee` to check for broken links in CI & fix broken links
  .github/workflows/broken-links.yml
  .lycheeignore
  README.md
Labels: kind/enhancement, kind/meta

#90 Update parse5 dependency & fix remaining broken links
  README.md
  ext/legal.html
  ext/lib/parse5.js
  package-lock.json
  package.json
Labels: area/dependencies

#91 Update manifest scripts: only support v3, and yomichan->yomitan
  dev/data/manifest-variants.json
  ext/manifest.json
  package.json
Labels: kind/enhancement, kind/meta

#93 Add OSSF scorecard action
  .github/workflows/scorecard.yml
Labels: kind/enhancement, kind/meta

#88 Make it easy to build project on Nix package manager / NixOS
  build.sh
  shell.nix
Labels: kind/enhancement, kind/meta

#95 Format ci.yml, update to checkout@v3, and restrict permissions to satisfy OSSF scorecard
  .github/workflows/ci.yml
Labels: kind/enhancement, kind/meta

#92 Add CD to build and publish extension to Chrome & Firefox stores
  .github/release.yml
  .github/workflows/ci.yml
  .github/workflows/create-prerelease-on-tag.yml
  .github/workflows/publish-chrome-development.yml
  .github/workflows/publish-chrome.yml
  .github/workflows/publish-firefox-development.yml
  .github/workflows/publish-firefox.yml
  .github/workflows/touch-google-refresh-token.yml
  .node-version
  dev/data/manifest-variants.json
Labels: kind/enhancement, kind/meta

#8 Apply .aac extension so playback works in downstream Anki clients
  ext/js/media/media-util.js
Labels: kind/bug

#107 Fix Google Docs URL regex to not be excessively wide
  ext/js/accessibility/accessibility-controller.js
Labels: kind/bug

#108 Fix playwright action so that it leaves comments even for PRs from forks
  .github/workflows/playwright.yml
  .github/workflows/playwright_comment.yml
Labels: kind/bug, kind/meta
