Repository yomidevs/yomitan, pull requests merged in 2024-09, with the labels that each got.

#1387 Add hindi language option.
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1324 Add top level read content permissions
  .github/workflows/bench.yml
  .github/workflows/codeql.yml
  .github/workflows/publish-edge.yml
  .github/workflows/release.yml
Labels: kind/meta, area/ci

#1386 added link of microsoft edge to ask for ratings and reviews
  ext/info.html
Labels: area/documentation

#1385 Refactor Japanese ます, んかった form
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/bug, area/linguistics

#1389 Add GITHUB_TOKEN
  .github/workflows/release.yml
Labels: area/ci

#1393 [ja] Add -ntosuru form
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1394 [ja] refactor irregular verbs + ksb -tari form
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1397 [ja] add volitional slang
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1399 [ja] add ~ておく conjugation
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1408 Make layoutAwareScan `true` by default
  ext/data/schemas/options-schema.json
Labels: kind/enhancement, area/ui-ux

#1410 Fix recommended dictionary download queue
  ext/js/pages/settings/dictionary-import-controller.js
Labels: kind/bug, area/ui-ux

#1412 Dictionary delete queue
  ext/js/pages/settings/dictionary-controller.js
Labels: kind/enhancement, area/ui-ux

#1423 Add `None` Popup Shadow Option
  ext/css/popup-outer.css
  ext/data/schemas/options-schema.json
  ext/js/app/theme-controller.js
  ext/settings.html
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux

#1424 Enable `jsonc/sort-keys` on `recommended-dictionaries.json`, Update `recommended-dictionaries-schema.json`
  .eslintrc.json
  .vscode/settings.json
  ext/data/recommended-dictionaries.json
  ext/data/schemas/recommended-dictionaries-schema.json
Labels: kind/meta

#1413 Refactor Japanese transforms
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/data/anki-note-builder-test-results.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1427 Not trigger search when touch on popup clickable components
  ext/js/language/text-scanner.js
  types/ext/input.d.ts
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#1437 Guard against frequency dicts with values of 0 or less
  ext/js/data/anki-note-data-creator.js
Labels: kind/bug, area/anki

#1441 Puts custom font-family setting in advanced
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1443 Allow scanning on input type = 'search'
  ext/js/dom/text-source-generator.js
Labels: kind/enhancement
