Repository yomidevs/yomitan, pull requests merged in 2024-08, with the labels that each got.

#1288 [ko] Fix -ida transforms
  ext/js/language/ko/korean-transforms.js
  test/language/korean-transforms.test.js
Labels: kind/bug, area/linguistics

#1270 Dictionary alias
  docs/anki-integration.md
  ext/css/settings.css
  ext/data/schemas/options-schema.json
  ext/data/templates/anki-field-templates-upgrade-v49.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/background/backend.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/anki-template-util.js
  ext/js/data/options-util.js
  ext/js/dictionary/dictionary-data-util.js
  ext/js/display/display-generator.js
  ext/js/dom/dom-data-binder.js
  ext/js/language/translator.js
  ext/js/pages/settings/dictionary-controller.js
  ext/settings.html
  ext/templates-settings.html
  ext/welcome.html
  test/anki-template-renderer.test.js
  test/data/anki-note-builder-test-results.json
  test/data/translator-test-inputs.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/database.test.js
  test/options-util.test.js
  types/ext/anki-templates.d.ts
  types/ext/dictionary-data-util.d.ts
  types/ext/dictionary.d.ts
  types/ext/dom-data-binder.d.ts
  types/ext/settings.d.ts
  types/ext/translation.d.ts
Labels: kind/enhancement, area/ui-ux

#1305 [de] add deinflection tests, add some deinflections
  ext/js/language/de/german-transforms.js
  test/language/german-transforms.test.js
  types/ext/language-transformer.d.ts
Labels: kind/enhancement, area/linguistics

#1306 Disconnect IPA text and "Downstep notation" appearance setting
  ext/css/display.css
  ext/js/display/display-generator.js
Labels: kind/enhancement, area/ui-ux

#1298 add audio for more languages from LanguagePod101
  docs/audio.md
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display-audio.js
  ext/js/media/audio-downloader.js
  ext/js/pages/settings/audio-controller.js
  ext/templates-settings.html
  test/options-util.test.js
  types/ext/audio-downloader.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/audio

#1308 Fix infinite event listener ping-pong destroying settings page
  ext/js/dom/dom-data-binder.js
Labels: kind/bug, area/performance, area/ui-ux, priority/high, regression

#1310 Reduce anki audio error level to log
  ext/js/background/backend.js
Labels: kind/enhancement, area/ui-ux

#1316 Add forvo to lycheeignore
  .github/workflows/broken-links.yml
  .lycheeignore
  README.md
Labels: kind/meta

#1318 Revert scorecard version
  .github/workflows/scorecard.yml
Labels: area/ci

#1335 Fix links to Extension Settings not working on Firefox
  ext/issues.html
  ext/permissions.html
  ext/welcome.html
Labels: kind/enhancement, area/ui-ux

#1336 Disable download button when dictionary is already installed
  ext/js/pages/settings/dictionary-import-controller.js
Labels: kind/bug, area/ui-ux

#1330 Whole word scanning
  ext/data/schemas/options-schema.json
  ext/js/app/frontend.js
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/dom/dom-text-scanner.js
  ext/js/dom/text-source-generator.js
  ext/js/dom/text-source-range.js
  ext/js/language/text-scanner.js
  ext/settings.html
  test/options-util.test.js
  types/ext/dom-text-scanner.d.ts
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#1351 Remove unneeded PointerEvent check in _onRecommendedImportClick
  ext/js/pages/settings/dictionary-import-controller.js
Labels: kind/bug, area/ui-ux

#1361 [ja] add 〜まい form
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1371 Fix naming of glossary-first handlebars in settings help modal
  ext/settings.html
Labels: kind/bug, area/ui-ux, area/anki
