Repository yomidevs/yomitan, pull requests merged in 2024-10, with the labels that each got.

#1452 Fix UTF32 characters breaking sentence parser due directly accessing string array indexes
  ext/js/dom/text-source-generator.js
Labels: kind/bug, area/anki

#1425 Create HTML templates for modals
  ext/js/display/search-main.js
  ext/js/pages/permissions-main.js
  ext/js/pages/settings/modal-controller.js
  ext/js/pages/settings/settings-main.js
  ext/js/pages/welcome-main.js
  ext/settings.html
  ext/templates-modals.html
  ext/welcome.html
Labels: kind/meta

#1457 Apply custom dict css when resetting settings
  ext/js/pages/settings/dictionary-controller.js
Labels: kind/bug, area/dictionary-format, area/ui-ux, area/anki

#1466 Update paths
  .github/dependabot.yml
  .github/workflows/playwright.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  dev/data/manifest-variants.json
  docs/advanced-options.md
  docs/audio.md
  docs/development/language-features.md
  docs/dictionaries.md
  docs/making-yomitan-dictionaries.md
  docs/operations/deployments.md
  docs/yomichan-migration.md
  ext/data/recommended-dictionaries.json
  ext/info.html
  ext/js/core/log.js
  ext/quick-start-guide.html
  ext/settings.html
  ext/templates-modals.html
  ext/welcome.html
  package.json
  test/playwright/visual.spec.js
Labels: kind/meta

#1476 Fix frequencies missing value to push to array
  ext/js/data/anki-note-data-creator.js
Labels: kind/bug, priority/high, area/anki, regression

#1475 [ja] Add 恋う irregular verb
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1482 Only display yomitan discord in readme
  README.md
Labels: area/documentation

#697 Begin to add performance marks
  ext/js/display/display.js
Labels: kind/meta, area/performance

#1473 ExtensionError when validating dictionary includes error cause
  ext/js/dictionary/dictionary-importer.js
Labels: kind/enhancement, area/ui-ux

#1464 Add term tags to `{tags}` Anki field
  ext/js/templates/anki-template-renderer.js
  test/data/anki-note-builder-test-results.json
Labels: kind/enhancement, area/anki

#1499 Fix No Dictionary Enabled settings link opening in a new tab (#1343)
  ext/popup.html
Labels: kind/enhancement, area/ui-ux

#1368 Support default setting overrides on different languages
  .eslintrc.json
  ext/data/recommended-settings.json
  ext/data/schemas/recommended-settings-schema.json
  ext/js/pages/settings/recommended-settings-controller.js
  ext/js/pages/settings/settings-controller.js
  ext/js/pages/settings/settings-main.js
  ext/js/pages/welcome-main.js
  ext/templates-modals.html
  ext/templates-settings.html
  test/data/json.json
  types/ext/settings-controller.d.ts
Labels: kind/enhancement, area/ui-ux

#1533 Fix UTF16 and UTF32 characters breaking cloze data due to the use of substring
  ext/js/data/anki-note-data-creator.js
Labels: kind/bug, area/anki

#1538 Allow scanning without moving mouse from clicking
  ext/js/display/display.js
  ext/js/display/query-parser.js
  ext/js/language/text-scanner.js
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#1497 Sort entries by primary reading
  ext/js/background/backend.js
  ext/js/display/display.js
  ext/js/language/translator.js
  test/data/anki-note-builder-test-results.json
  test/data/database-test-cases.json
  test/data/dictionaries/valid-dictionary1/term_bank_1.json
  test/data/translator-test-inputs.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/utilities/translator.js
  types/ext/api.d.ts
  types/ext/dictionary.d.ts
  types/ext/translation.d.ts
  types/test/translator.d.ts
Labels: kind/enhancement
