Repository yomidevs/yomitan, pull requests merged in 2024-06, with the labels that each got.

#1000 display inflection rule descriptions
  ext/css/display.css
  ext/data/templates/anki-field-templates-upgrade-v38.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  ext/js/display/display-generator.js
  ext/js/display/display.js
  ext/js/language/de/german-transforms.js
  ext/js/language/en/english-transforms.js
  ext/js/language/es/spanish-transforms.js
  ext/js/language/ja/japanese-transforms.js
  ext/js/language/ko/korean-transforms.js
  ext/js/language/la/latin-transforms.js
  ext/js/language/language-transformer.js
  ext/js/language/multi-language-transformer.js
  ext/js/language/sga/old-irish-transforms.js
  ext/js/language/sq/albanian-transforms.js
  ext/js/language/translator.js
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/language/japanese-transforms.test.js
  test/options-util.test.js
  types/ext/dictionary.d.ts
  types/ext/language-transformer-internal.d.ts
  types/ext/language-transformer.d.ts
  types/ext/translation-internal.d.ts
  types/ext/translator.d.ts
Labels: kind/enhancement, area/ui-ux

#1032 escape dictionary name for dynamic handlebars
  ext/js/data/anki-template-util.js
Labels: kind/bug, area/anki

#1040 demolished duplicate "adjust"
  ext/settings.html
Labels: area/documentation

#1051 Fix semantics of disallowExpandSelection
  ext/js/dom/text-source-range.js
Labels: area/tech-debt

#1050 Handle Unchecked runtime.lastError: Cannot create item with duplicate…
  ext/js/background/backend.js
Labels: kind/bug

#1063 Error check context menu editing
  ext/js/background/backend.js
Labels: kind/bug

#933 Add web option to profile switching keybinds
  ext/data/schemas/options-schema.json
  ext/js/app/frontend.js
  ext/js/data/options-util.js
  ext/js/data/profiles-util.js
  ext/js/display/display.js
  ext/js/pages/settings/keyboard-shortcuts-controller.js
  test/options-util.test.js
Labels: kind/enhancement, area/ui-ux

#1065 Don't move offset when disallowExpandSelection is true
  ext/js/dom/text-source-range.js
Labels: kind/bug

#1071 Fix DOMTextScanner entering initial div on backwards seeks
  .vscode/launch.json
  ext/js/dom/dom-text-scanner.js
  test/data/html/text-source-range.html
  test/data/json.json
  test/dom-text-scanner.test.js
  test/text-source-range.test.js
Labels: kind/bug

#1079 Add full dark mode support
  ext/css/action-popup.css
  ext/css/material.css
  ext/css/popup-preview.css
  ext/css/settings.css
  ext/js/pages/action-popup-main.js
  ext/js/pages/info-main.js
  ext/js/pages/permissions-main.js
  ext/js/pages/quick-start-guide-main.js
  ext/js/pages/settings/popup-preview-frame.js
  ext/js/pages/settings/settings-display-controller.js
  ext/js/pages/settings/settings-main.js
  ext/js/pages/welcome-main.js
  ext/permissions.html
  ext/popup-preview.html
  ext/quick-start-guide.html
  ext/settings.html
  ext/welcome.html
Labels: kind/enhancement, area/ui-ux

#1084 Fix auto popup theme shadow not applying
  ext/js/app/theme-controller.js
Labels: kind/bug, area/ui-ux

#1086 Add auto option to body theme
  ext/css/popup-preview.css
  ext/data/schemas/options-schema.json
  ext/js/app/frontend.js
  ext/js/app/theme-controller.js
  ext/js/display/display.js
  ext/js/display/query-parser.js
  ext/js/language/text-scanner.js
  ext/js/pages/action-popup-main.js
  ext/js/pages/info-main.js
  ext/js/pages/quick-start-guide-main.js
  ext/js/pages/settings/popup-preview-frame.js
  ext/js/pages/settings/settings-display-controller.js
  ext/settings.html
  ext/welcome.html
  types/ext/display.d.ts
  types/ext/query-parser.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#1088 Remove flickering on page loads, reduce flashbangs, fix settings and popup themes applying correctly
  ext/action-popup.html
  ext/css/popup-preview.css
  ext/info.html
  ext/js/display/display.js
  ext/js/display/search-main.js
  ext/js/pages/action-popup-main.js
  ext/js/pages/info-main.js
  ext/js/pages/permissions-main.js
  ext/js/pages/quick-start-guide-main.js
  ext/js/pages/settings/settings-display-controller.js
  ext/js/pages/settings/settings-main.js
  ext/js/pages/welcome-main.js
  ext/permissions.html
  ext/quick-start-guide.html
  ext/search.html
  ext/settings.html
  ext/welcome.html
Labels: kind/enhancement, area/ui-ux

#1090 Show loading message before action popup is loaded
  ext/action-popup.html
  ext/css/action-popup.css
  ext/js/pages/action-popup-main.js
Labels: kind/enhancement, area/ui-ux

#1094 Set up down buttons to default button size when on mobile
  ext/css/settings.css
Labels: kind/enhancement, area/ui-ux

#1095 Add modal-body to scrollbar styling
  ext/css/settings.css
Labels: kind/bug, area/ui-ux

#1089 Fix shadow in popup preview when auto is selected
  ext/js/app/popup.js
  ext/js/display/display.js
  ext/js/pages/settings/popup-preview-controller.js
Labels: kind/bug, area/ui-ux

#1097 Fix missing legal-npm.html
  .gitignore
  dev/data/legal-npm.css
  ext/legal-npm.html
Labels: kind/bug, area/documentation

#1080 support css file in dictionaries
  benches/translator.bench.js
  ext/data/templates/anki-field-templates-upgrade-v41.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/anki-note-builder.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/options-util.js
  ext/js/dictionary/dictionary-importer.js
  ext/js/display/display-anki.js
  ext/js/display/display.js
  ext/js/pages/settings/dictionary-controller.js
  ext/js/pages/settings/dictionary-import-controller.js
  test/anki-template-renderer.test.js
  test/data/anki-note-builder-test-results.json
  test/data/database-test-cases.json
  test/data/dictionaries/valid-dictionary1/styles.css
  test/data/translator-test-results-note-data1.json
  test/dictionary-data.test.js
  test/dictionary-data.write.js
  test/fixtures/translator-test.js
  test/options-util.test.js
  test/utilities/anki.js
  types/ext/anki-note-builder.d.ts
  types/ext/anki-templates-internal.d.ts
  types/ext/anki-templates.d.ts
  types/ext/dictionary-importer.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/dictionary-format

#1099 Use browser theme for loading on action popup
  ext/css/action-popup.css
Labels: kind/enhancement, area/ui-ux

#1101 Remove flashbangs on page transition
  ext/css/settings.css
Labels: kind/enhancement, area/ui-ux

#1102 Remove search page flashbang on page transition
  ext/css/search.css
Labels: kind/enhancement, area/ui-ux

#1105 Add profile selector to mobile action-popup
  ext/action-popup.html
  ext/css/action-popup.css
  ext/js/pages/action-popup-main.js
Labels: kind/bug, area/ui-ux, platform/android-only

#1110 fix dictionaryStylesMap undefined when testing anki templates
  ext/js/pages/settings/anki-templates-controller.js
Labels: kind/bug, area/anki

#1115 Fix firefox search button 1px off of search textbox
  ext/css/search.css
  ext/js/display/search-display-controller.js
Labels: kind/bug, browser/firefox, area/ui-ux

#1114 Make search header sticky
  ext/css/display.css
  ext/css/search.css
  ext/search.html
Labels: kind/enhancement, area/ui-ux

#1111 Cleanup and center custom css modal
  ext/css/settings.css
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1112 Support dictionaryStylesMap in anki-deck-generator-controller and anki-templates-controller
  ext/js/data/anki-note-builder.js
  ext/js/display/display-anki.js
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/js/pages/settings/anki-templates-controller.js
Labels: kind/bug, priority/high, area/anki

#1126 Auto resize search textbox when removing lines
  ext/css/search.css
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#1127 Make search sizing more sensible due to search textbox and query now being sticky
  ext/css/display.css
  ext/css/search.css
Labels: kind/bug, area/ui-ux

#1130 Update theme after search update in popup preview
  ext/js/pages/settings/popup-preview-frame.js
Labels: kind/bug, area/ui-ux

#1131 Fix alt+scroll offset from elements above sticky header
  ext/js/display/display.js
  ext/search.html
Labels: kind/bug, area/ui-ux

#1103 Add Documentation for Making Dictionaries
  README.md
  docs/making-yomitan-dictionaries.md
Labels: area/documentation

#1136 Add normalization of combining dakuten and handakuten to ja preprocessors
  ext/js/language/ja/japanese-text-preprocessors.js
  ext/js/language/ja/japanese.js
  ext/js/language/language-descriptors.js
  test/language/japanese-preprocessors.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1139 Add support for preprocessing halfwidth nakaguro
  ext/js/language/ja/japanese.js
Labels: kind/enhancement, area/linguistics

#1141 Attempt to fallback on kanji or terms dict when no results are found in the other
  ext/js/display/display.js
Labels: kind/enhancement

#1144 update language features docs to mention iso639_3
  docs/development/language-features.md
Labels: area/documentation

#1146 [mn] add Mongolian
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1134 Korean transformation tests
  test/fixtures/language-transformer-test.js
  test/language/korean-transforms.test.js
Labels: area/linguistics

#1148 Update language features docs
  docs/development/language-features.md
  test/language/english-transforms.test.js
Labels: area/documentation, kind/enhancement

#1143 Add wiktionary commons audio source
  ext/data/schemas/options-schema.json
  ext/js/display/display-audio.js
  ext/js/media/audio-downloader.js
  ext/js/media/media-util.js
  ext/js/pages/settings/audio-controller.js
  ext/templates-settings.html
  types/ext/audio-downloader.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/audio
