Repository yomidevs/yomitan, pull requests merged in 2024-03, with the labels that each got.

#732 Mark string and text glossary content as safe to avoid broken <br>
  ext/js/templates/sandbox/anki-template-renderer.js
Labels: kind/bug

#733 Fix sentence-furigana template
  ext/data/templates/anki-field-templates-upgrade-v27.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  test/options-util.test.js
Labels: kind/bug

#757 Ci updates
  .github/workflows/ci.yml
  package.json
  test/data/vitest.options.config.json
  test/data/vitest.write.config.json
  test/dictionary-data.write.js
Labels: kind/meta

#752 enable new dicts only on edited profile
  ext/js/pages/settings/dictionary-import-controller.js
Labels: kind/enhancement, area/ui-ux

#754 Fix entry selection arrow padding in search
  ext/css/search.css
Labels: kind/bug, area/ui-ux

#755 preserve whitespace in cloze-prefix and cloze-suffix
  ext/data/templates/anki-field-templates-upgrade-v27.handlebars
  ext/data/templates/anki-field-templates-upgrade-v28.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  ext/js/templates/sandbox/template-renderer.js
  test/options-util.test.js
Labels: kind/bug

#756 add more arabic diacritics
  ext/js/language/ar/arabic-text-preprocessors.js
Labels: kind/enhancement, area/grammar

#758 Correct README English
  README.md
Labels: kind/meta

#759 Support build.js target positional arguments
  dev/bin/build.js
Labels: kind/bug

#762 add arabic diacritics: maddah, hamza, subscript and superscript alef
  ext/js/language/ar/arabic-text-preprocessors.js
Labels: kind/enhancement, area/linguistics

#731 Move sandbox files
  .eslintrc.json
  dev/jsconfig.json
  docs/templates.md
  ext/js/background/backend.js
  ext/js/background/offscreen-proxy.js
  ext/js/background/offscreen.js
  ext/js/data/anki-note-builder.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/array-buffer-util.js
  ext/js/data/string-util.js
  ext/js/display/display-content-manager.js
  ext/js/display/display-generator.js
  ext/js/display/pronunciation-generator.js
  ext/js/display/structured-content-generator.js
  ext/js/dom/css-style-applier.js
  ext/js/dom/dom-text-scanner.js
  ext/js/dom/text-source-element.js
  ext/js/media/audio-downloader.js
  ext/js/pages/settings/backup-controller.js
  ext/js/templates/anki-template-renderer-content-manager.js
  ext/js/templates/anki-template-renderer.js
  ext/js/templates/template-renderer-frame-api.js
  ext/js/templates/template-renderer-frame-main.js
  ext/js/templates/template-renderer-media-provider.js
  ext/js/templates/template-renderer.js
  ext/template-renderer.html
  test/eslint-config.test.js
  test/fixtures/anki-template-renderer-test.js
  test/utilities/anki.js
Labels: kind/meta

#769 feat: support skipping already import dictionaries
  ext/js/dictionary/dictionary-importer.js
  ext/js/pages/settings/dictionary-import-controller.js
  test/database.test.js
  types/ext/dictionary-importer.d.ts
  types/ext/dictionary-worker.d.ts
Labels: kind/enhancement, area/ui-ux

#774 add suru verb masu stem deinflection
  ext/js/language/ja/japanese-transforms.json
  test/language-transformer.test.js
Labels: kind/enhancement, area/linguistics

#745 expand deinflection format
  .eslintrc.json
  benches/language-transformer.bench.js
  ext/js/background/backend.js
  ext/js/background/offscreen-proxy.js
  ext/js/background/offscreen.js
  ext/js/language/de/german-transforms.js
  ext/js/language/en/english-transforms.js
  ext/js/language/en/english-transforms.json
  ext/js/language/ja/japanese-transforms.js
  ext/js/language/ja/japanese-transforms.json
  ext/js/language/language-descriptors.js
  ext/js/language/language-transformer.js
  ext/js/language/language-transforms.js
  ext/js/language/languages.js
  ext/js/language/multi-language-transformer.js
  ext/js/language/sq/albanian-transforms.js
  ext/js/language/translator.js
  test/data/json.json
  test/fixtures/translator-test.js
  test/language-transformer-cycles.test.js
  test/language-transformer.test.js
  types/ext/language-descriptors.d.ts
  types/ext/language-transformer-internal.d.ts
  types/ext/language-transformer.d.ts
  types/ext/language.d.ts
  types/ext/offscreen.d.ts
Labels: kind/enhancement, area/linguistics
