Repository yomidevs/yomitan, pull requests merged in 2024-11, with the labels that each got.

#1559 Add radical normalization preprocessor to Japanese, Chinese, and Cantonese
  .eslintrc.json
  ext/js/language/CJK-util.js
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1527 Fix example text popup not updating correctly when scan resolution is set to `word`
  ext/js/app/frontend.js
  ext/js/dom/dom-text-scanner.js
  ext/js/dom/text-source-range.js
  ext/js/language/text-scanner.js
  types/ext/text-scanner.d.ts
Labels: kind/bug, area/ui-ux

#1565 Restore searchOnClick for search page
  ext/js/display/display.js
  ext/js/display/query-parser.js
  ext/js/language/text-scanner.js
  types/ext/text-scanner.d.ts
Labels: kind/bug, area/ui-ux, regression

#1542 Force scan resolution "character" for ja, zh, yue, and ko
  ext/css/search-settings.css
  ext/css/settings.css
  ext/css/visibility-modifiers.css
  ext/js/language/text-scanner.js
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1574 Fix "Import dictionaries from URLs" textarea not showing newlines on firefox
  ext/css/settings.css
Labels: kind/bug, browser/firefox, area/ui-ux

#1561 Allow queueing dictionary update & delete together
  ext/js/pages/settings/dictionary-controller.js
  ext/js/pages/settings/dictionary-import-controller.js
  types/ext/dictionary-controller.d.ts
  types/ext/settings-controller.d.ts
Labels: kind/enhancement, area/ui-ux

#1571 Show Anki card flags
  ext/css/material.css
  ext/data/schemas/options-schema.json
  ext/images/flag.svg
  ext/js/background/backend.js
  ext/js/comm/anki-connect.js
  ext/js/data/options-util.js
  ext/js/display/display-anki.js
  ext/settings.html
  ext/templates-display.html
  test/options-util.test.js
  types/ext/anki.d.ts
  types/ext/display-anki.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux, area/anki

#1588 Add sourcesZipFilePath to publish firefox
  .github/workflows/publish-firefox.yml
Labels: kind/meta, area/ci

#1591 Add TTS Anki Warning
  ext/templates-modals.html
  ext/templates-settings.html
Labels: kind/enhancement, area/ui-ux

#1597 Add build instructions to readme
  README.md
Labels: area/documentation

#1592 Add turning-off of parser for languages with spaces in recommended settings
  ext/data/recommended-settings.json
Labels: kind/enhancement, area/ui-ux

#1525 Redid the Action Popup
  ext/action-popup.html
  ext/css/action-popup.css
  ext/js/pages/action-popup-main.js
Labels: kind/enhancement, area/ui-ux

#1599 Fix disabled scan resolution in ja, zh, yue, and ko
  ext/js/language/text-scanner.js
Labels: kind/bug

#1600 Trim search query strings to prevent newlines expanding search page
  ext/js/display/query-parser.js
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#1606 Remove dictionary priority from settings
  ext/css/settings.css
  ext/data/schemas/options-schema.json
  ext/js/background/backend.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/options-util.js
  ext/js/language/translator.js
  ext/js/pages/settings/dictionary-controller.js
  ext/templates-modals.html
  ext/templates-settings.html
  test/anki-template-renderer.test.js
  test/data/translator-test-inputs.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/database.test.js
  test/options-util.test.js
  types/ext/anki-templates.d.ts
  types/ext/dictionary.d.ts
  types/ext/settings.d.ts
  types/ext/translation.d.ts
Labels: kind/enhancement, area/ui-ux

#1617 Fixed issue #1607 updated reame removed typos
  README.md
Labels: area/documentation

#1619 Fixed spacing and moved tabindex in the action popup
  ext/action-popup.html
  ext/css/action-popup.css
Labels: kind/bug, area/ui-ux

#1621 Update good first issue link
  README.md
Labels: area/documentation

#1625 Fix whitespace trimming in search page
  ext/js/data/string-util.js
  ext/js/display/query-parser.js
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#1618 Normalize CJK Compatibility characters
  ext/js/language/CJK-util.js
  ext/js/language/ja/japanese-text-preprocessors.js
  ext/js/language/ja/japanese.js
  ext/js/language/language-descriptors.js
  test/japanese-util.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1608 Show metadata when clicking on term, kanji, and frequency dictionary tags
  ext/js/dictionary/dictionary-data-util.js
  ext/js/display/display-generator.js
  ext/js/display/display.js
  types/ext/dictionary-data-util.d.ts
Labels: kind/enhancement, area/ui-ux
