Repository yomidevs/yomitan, pull requests merged in 2024-05, with the labels that each got.

#833 add some Japanese transforms
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#857 Fix definition.cloze and text-based getMedia in handlebars being escaped
  ext/data/templates/anki-field-templates-upgrade-v33.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  test/options-util.test.js
Labels: kind/bug, area/anki

#814 add single dictionary handlebars
  docs/anki-integration.md
  ext/data/templates/anki-field-templates-upgrade-v34.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/anki-template-util.js
  ext/js/data/anki-util.js
  ext/js/data/options-util.js
  ext/js/display/display-anki.js
  ext/js/pages/settings/anki-controller.js
  ext/js/pages/settings/anki-templates-controller.js
  ext/settings.html
  test/options-util.test.js
Labels: kind/enhancement, area/anki

#885 Fix Term display style and Reading mode css conflict
  ext/css/display.css
Labels: kind/bug, area/ui-ux

#886 Fix mobile action-popup
  ext/action-popup.html
  ext/css/action-popup.css
  ext/js/pages/action-popup-main.js
Labels: kind/enhancement, area/ui-ux

#890 Fix action-popup toggle being elongated on desktop
  ext/css/action-popup.css
Labels: kind/bug, area/ui-ux

#894 Change Details and Summary Tags CSS
  dev/data/structured-content-overrides.css
  ext/css/structured-content.css
Labels: area/ui-ux

#901 add a few deinflections for Latin
  .eslintrc.json
  ext/js/language/la/latin-transforms.js
  ext/js/language/language-descriptors.js
  test/language/latin-transforms.test.js
Labels: kind/enhancement, area/linguistics

#909 Prevent updating dict entry details for anki when anki is disabled
  ext/js/display/display-anki.js
Labels: kind/bug, area/anki

#914 Allow ctrl + backspace to refocus the search
  ext/js/display/search-display-controller.js
Labels: kind/enhancement, area/ui-ux

#895 Add option to bulk generate anki cards
  docs/anki-integration.md
  ext/css/settings.css
  ext/js/comm/anki-connect.js
  ext/js/pages/settings/anki-controller.js
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/js/pages/settings/settings-main.js
  ext/settings.html
Labels: kind/enhancement, area/anki

#924 Fix Frequency sorting dictionary setting dropdown showing all dictionaries instead of only dictionaries with frequency data
  ext/js/pages/settings/sort-frequency-dictionary-controller.js
Labels: kind/bug, area/ui-ux, regression

#920 Restore shift click behavior for search button opening as a popup
  ext/js/background/backend.js
  ext/js/pages/action-popup-main.js
Labels: kind/bug, area/ui-ux, regression

#884 Rework settings
  ext/css/material.css
  ext/images/monitor.svg
  ext/js/pages/settings/recommended-permissions-controller.js
  ext/js/pages/welcome-main.js
  ext/quick-start-guide.html
  ext/settings.html
  ext/welcome.html
Labels: kind/enhancement, area/ui-ux

#921 Add glossary-first handlebars
  docs/anki-integration.md
  ext/data/templates/anki-field-templates-upgrade-v35.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/anki-template-util.js
  ext/js/data/options-util.js
  ext/settings.html
  test/data/anki-note-builder-test-results.json
  test/options-util.test.js
Labels: kind/enhancement, area/anki

#932 Add permissions page link in settings
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#930 Catch and handle errors if getOptionsFull fails
  ext/js/pages/settings/dictionary-import-controller.js
Labels: kind/bug, browser/firefox, priority/high

#916 Allow keyboard shortcut hotkeys to be modifiers only
  ext/js/input/hotkey-handler.js
Labels: kind/bug, area/ui-ux

#787 add korean
  .eslintrc.json
  README.md
  dev/lib/hangul-js.js
  docs/dictionaries.md
  ext/js/language/ko/korean-text-processors.js
  ext/js/language/ko/korean-transforms.js
  ext/js/language/language-descriptors.js
  package-lock.json
  package.json
  test/data/anki-note-builder-test-results.json
  test/data/database-test-cases.json
  test/data/dictionaries/valid-dictionary1/term_bank_1.json
  test/data/translator-test-inputs.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#917 Cache mousemove and hook keyboard to allow scanning at mouse position while mouse is no longer moving
  ext/js/language/text-scanner.js
Labels: kind/enhancement, area/ui-ux

#934 Update anki settings when Configure Anki card format button is clicked instead of requiring page refresh
  ext/js/pages/settings/anki-controller.js
Labels: kind/enhancement, area/ui-ux

#915 Make Scan selected text lazy and add Scan text at selection
  ext/js/app/frontend.js
  ext/js/dom/text-source-range.js
  ext/js/pages/settings/keyboard-shortcuts-controller.js
  ext/templates-settings.html
Labels: kind/enhancement, area/ui-ux

#938 fix search resolution infinite loop
  ext/js/language/translator.js
Labels: kind/bug, priority/high

#940 Fix collection import error and progress display
  ext/settings.html
Labels: kind/bug, regression

#942 Allow setting optional permissions on welcome page
  ext/js/pages/settings/recommended-permissions-controller.js
  ext/welcome.html
Labels: kind/enhancement, area/ui-ux

#958 Disallow scanning while mouse is not moving if input, textarea, or editable elements are active
  ext/js/language/text-scanner.js
Labels: kind/enhancement, area/ui-ux

#959 Disallow hotkeys with no keys or modifiers
  ext/js/input/hotkey-handler.js
Labels: kind/bug, area/ui-ux

#963 Add Lao language
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement

#962 refactor svg code for icons
  ext/images/add-duplicate-term-kana-blue.svg
  ext/images/add-duplicate-term-kana.svg
  ext/images/add-duplicate-term-kanji-blue.svg
  ext/images/add-duplicate-term-kanji.svg
  ext/images/add-term-kana.svg
  ext/images/add-term-kanji.svg
Labels: area/tech-debt

#966 Add word wrap to #extension-info on mobile to prevent page horizontal elongation
  ext/css/action-popup.css
Labels: kind/enhancement, area/ui-ux

#970 Add up to date screenshots
  img/ss-anki-thumb.png
  img/ss-anki.png
  img/ss-dictionaries-thumb.png
  img/ss-dictionaries.png
  img/ss-kanji-thumb.png
  img/ss-kanji.png
  img/ss-terms-thumb.png
  img/ss-terms.png
Labels: area/documentation

#960 Add onyomi-hiragana handlebars
  docs/anki-integration.md
  ext/data/templates/anki-field-templates-upgrade-v36.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/anki-template-util.js
  ext/js/data/options-util.js
  ext/settings.html
  test/data/anki-note-builder-test-results.json
  test/options-util.test.js
Labels: kind/enhancement, area/anki

#976 Add Cantonese
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#859 add support for overwriting existing card
  ext/css/display.css
  ext/data/schemas/options-schema.json
  ext/images/add-duplicate-term-kana.svg
  ext/images/add-duplicate-term-kanji.svg
  ext/images/overwrite-term-kana.svg
  ext/images/overwrite-term-kanji.svg
  ext/js/background/backend.js
  ext/js/comm/anki-connect.js
  ext/js/comm/api.js
  ext/js/data/anki-util.js
  ext/js/display/display-anki.js
  ext/js/pages/settings/anki-controller.js
  ext/settings.html
  ext/templates-display.html
  types/ext/anki.d.ts
  types/ext/api.d.ts
  types/ext/display-anki.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/anki

#972 Update anki settings on Configure Anki card format click
  ext/js/pages/settings/anki-controller.js
Labels: kind/bug, area/ui-ux

#981 Allow ordering term dictionaries with the same priority using the ui order
  ext/js/language/translator.js
Labels: kind/bug, area/ui-ux

#982 Remove No pitch accent data from pitch handlebars
  ext/data/templates/anki-field-templates-upgrade-v37.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  test/data/anki-note-builder-test-results.json
  test/options-util.test.js
Labels: kind/enhancement, area/anki

#965 Browser agnostic search page clipboard and selection handling
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#971 Move dictionary up and down buttons out of kebab menu
  ext/css/material.css
  ext/css/settings.css
  ext/images/down-chevron.svg
  ext/images/up-chevron.svg
  ext/js/pages/settings/dictionary-controller.js
  ext/settings.html
  ext/templates-settings.html
Labels: kind/enhancement, area/ui-ux

#898 Update issue templates
  .github/ISSUE_TEMPLATE/tech-debt.md
Labels: kind/meta

#979 Fix HTML lang tags not matching the selected language
  ext/css/display.css
  ext/js/display/display-generator.js
  ext/js/display/display.js
  ext/js/display/query-parser.js
  ext/js/display/search-display-controller.js
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/js/pages/settings/anki-templates-controller.js
  ext/js/pages/settings/settings-main.js
Labels: kind/bug, area/ui-ux

#937 Rework dictionary import UX
  ext/css/settings.css
  ext/js/pages/settings/dictionary-import-controller.js
  ext/js/pages/welcome-main.js
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#984 Add check for counts and counts.termMeta
  ext/js/pages/settings/sort-frequency-dictionary-controller.js
Labels: kind/bug

#973 improve preprocessing performance
  ext/js/language/translator.js
  types/ext/translation-internal.d.ts
Labels: kind/enhancement, area/performance

#964 [ja] add preprocessor for width of alphabetic characters
  ext/js/language/ja/japanese-text-preprocessors.js
  ext/js/language/ja/japanese.js
  ext/js/language/language-descriptors.js
  test/data/anki-note-builder-test-results.json
  test/data/database-test-cases.json
  test/data/dictionaries/valid-dictionary1/term_bank_1.json
  test/data/translator-test-inputs.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/japanese-util.test.js
  types/ext/language-descriptors.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/linguistics

#986 Fix detection of modifiers on Firefox in textarea or input and modifiers sent through virtual keycodes
  ext/js/dom/document-util.js
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#908 Basic Spanish Transforms
  .eslintrc.json
  ext/js/core/log.js
  ext/js/language/es/spanish-transforms.js
  ext/js/language/language-descriptors.js
  ext/js/language/language-transformer.js
  ext/js/language/language-transforms.js
  test/language/spanish-transforms.test.js
  types/ext/language-transformer-internal.d.ts
  types/ext/language-transformer.d.ts
Labels: kind/enhancement, area/linguistics

#999 Add and Reorganize Docs
  README.md
Labels: area/documentation

#997 Fix chance of multiple popups appearing when scan key is pressed multiple times without moving
  ext/js/app/frontend.js
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#992 Change mode to enum
  ext/js/background/backend.js
  types/ext/backend.d.ts
Labels: area/tech-debt

#998 Mention Browser TTS Options in Docs
  docs/audio.md
Labels: area/documentation

#985 Removed normalizeTermOrReading
  ext/js/dictionary/dictionary-importer.js
Labels: area/tech-debt

#1003 Fix clipboard monitor in popups
  ext/js/background/backend.js
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#1004 Add note about refreshing page in api invoke error
  ext/js/comm/api.js
Labels: kind/enhancement, area/ui-ux

#1006 Disallow breaking on rb tags when layout aware scanning is enabled
  ext/js/dom/dom-text-scanner.js
Labels: kind/bug, browser/firefox
