Repository yomidevs/yomitan, pull requests merged in 2024-07, with the labels that each got.

#1155 Set overscroll to contain for popup
  ext/css/display.css
Labels: kind/enhancement, area/ui-ux

#1157 Fix dark/light mode footer message box colors
  ext/css/display.css
  ext/templates-display.html
Labels: kind/enhancement, area/ui-ux

#1152 make non-ja audio work without configuration
  docs/audio.md
  ext/data/schemas/options-schema.json
  ext/js/display/display-audio.js
  ext/js/media/audio-downloader.js
  ext/js/pages/settings/audio-controller.js
Labels: kind/enhancement, area/audio

#1164 update readme mention of native audio
  README.md
Labels: area/documentation

#1169 Add Option for Scanning Alt Text
  ext/data/schemas/options-schema.json
  ext/js/app/frontend.js
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/language/text-scanner.js
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement

#1167 Remove preparing themecontroller on parent page to avoid css collisions changing themes on the parent page
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#1178 Override Search text with non-Japanese characters when language is not Japanese
  ext/js/language/translator.js
Labels: kind/enhancement

#1176 [en] simplify parts of speech to fix phrasal verbs
  ext/js/language/en/english-transforms.js
Labels: area/linguistics

#1179 [en] fix phrasal verbs with interposed 'it' or 'one'
  ext/js/language/en/english-transforms.js
  test/language/english-transforms.test.js
Labels: kind/bug, area/linguistics

#1188 Add option for sticky search header
  ext/css/display.css
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/search.html
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux

#1191 Allow enter button to search on android
  ext/js/display/search-display-controller.js
Labels: kind/enhancement, area/ui-ux

#1190 Fix search bar padding not matching when sticky header is disabled
  ext/css/display.css
Labels: kind/bug, area/ui-ux

#1193 allow more iso 639-3 codes
  ext/data/schemas/dictionary-index-schema.json
Labels: kind/bug, area/dictionary-format

#1194 Focus document focus controller element on the search page after body is unhidden
  ext/js/display/search-main.js
  ext/js/dom/document-focus-controller.js
Labels: kind/bug, area/ui-ux

#1189 Add search settings modal
  ext/css/search-settings.css
  ext/css/search.css
  ext/js/display/search-display-controller.js
  ext/js/display/search-main.js
  ext/search.html
Labels: kind/enhancement, area/ui-ux

#1196 Update CONTRIBUTING.md with instructions on how to load unpackaged build into Chrome
  CONTRIBUTING.md
Labels: area/documentation

#1202 Add contextMenus permission
  docs/permissions.md
  ext/permissions.html
Labels: area/documentation, kind/enhancement

#1208 Fix match result select trailing emphatic characters (っッー)
  ext/js/language/ja/japanese.js
  test/japanese-util.test.js
Labels: kind/bug

#1200 Sort dictionary entries by number of text processors applied
  ext/js/language/translator.js
  test/data/translator-test-results.json
  types/ext/dictionary.d.ts
  types/ext/translation-internal.d.ts
Labels: kind/bug, area/linguistics

#1207 Rename `{selection-text}` to `{popup-selection-text}`
  docs/anki-integration.md
  docs/templates.md
  ext/data/templates/anki-field-templates-upgrade-v45.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/app/frontend.js
  ext/js/data/anki-note-builder.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/anki-template-util.js
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/templates/template-renderer-media-provider.js
  ext/settings.html
  test/data/anki-note-builder-test-results.json
  test/options-util.test.js
  types/ext/anki-note-builder.d.ts
  types/ext/anki-templates.d.ts
  types/ext/cross-frame-api.d.ts
Labels: kind/meta, area/anki

#1210 Fix font settings defaults not appearing in settings ui
  ext/data/schemas/options-schema.json
Labels: kind/bug, area/ui-ux

#1209 Update Dictionaries, Replace with Kuuube BCCWJ
  docs/dictionaries.md
Labels: area/documentation, kind/enhancement

#1211 Fix setting page theme not updating when reset button is pressed
  ext/js/pages/settings/backup-controller.js
Labels: kind/bug, area/ui-ux

#1213 [tl] Add diacritics removal preprocessors
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1215 [zh] Update Chinese normalizer regex
  ext/js/language/zh/chinese.js
  test/language/chinese-reading-normalizer.test.js
Labels: kind/enhancement, area/dictionary-format

#1223 Fix supported languages link in readme
  README.md
Labels: area/documentation

#1221 Clear cached mouse position on mouseout
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#1214 Fix Firefox scanning when some combining characters are present
  ext/js/accessibility/google-docs-util.js
  ext/js/dom/document-util.js
  ext/js/dom/text-source-generator.js
  ext/js/language/text-scanner.js
  test/document-util.test.js
  types/ext/document-util.d.ts
Labels: kind/bug, browser/firefox

#1227 Avoid collapse leading and trailing emphatics
  ext/js/language/ja/japanese.js
  test/japanese-util.test.js
Labels: kind/bug, area/linguistics

#1220 Add helper text when search with no dictionaries enabled
  ext/js/display/display.js
  ext/popup.html
  ext/search.html
Labels: kind/enhancement, area/ui-ux

#1234 Set Empty Default Font
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  test/options-util.test.js
Labels: kind/bug, area/ui-ux

#1237 [it] preprocess italian diacritics
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1229 Stricten condition types
  docs/development/language-features.md
  ext/js/language/de/german-transforms.js
  ext/js/language/en/english-transforms.js
  ext/js/language/es/spanish-transforms.js
  ext/js/language/ja/japanese-transforms.js
  ext/js/language/ko/korean-transforms.js
  ext/js/language/la/latin-transforms.js
  ext/js/language/language-transforms.js
  ext/js/language/sga/old-irish-transforms.js
  ext/js/language/sq/albanian-transforms.js
  types/ext/language-transformer.d.ts
Labels: kind/meta

#1240 Fix audio menu z-index
  ext/css/material.css
Labels: kind/bug, area/ui-ux

#1233 playwright test importing from url and deleting dictionary
  test/playwright/visual.spec.js
Labels: kind/meta

#1241 Prevent popup scaling from throwing errors constantly
  ext/js/app/popup.js
Labels: kind/bug

#1230 show downloading dictionary in steps when importing from URL
  ext/js/dictionary/dictionary-importer.js
  ext/js/pages/settings/dictionary-import-controller.js
  test/database.test.js
  types/ext/dictionary-importer.d.ts
Labels: kind/enhancement, area/ui-ux

#1174 support updatable dictionaries
  ext/css/settings.css
  ext/data/schemas/dictionary-index-schema.json
  ext/js/dictionary/dictionary-data-util.js
  ext/js/dictionary/dictionary-importer.js
  ext/js/pages/settings/collapsible-dictionary-controller.js
  ext/js/pages/settings/dictionary-controller.js
  ext/js/pages/settings/dictionary-import-controller.js
  ext/js/pages/settings/secondary-search-dictionary-controller.js
  ext/settings.html
  ext/templates-settings.html
  ext/welcome.html
  test/dictionary-data-util.test.js
  types/ext/dictionary-data.d.ts
  types/ext/dictionary-importer.d.ts
  types/ext/settings-controller.d.ts
Labels: kind/enhancement, area/dictionary-format

#1246 [en] add -able deinflection rule
  ext/js/language/en/english-transforms.js
  test/language/english-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1247 Hide "Search text with non-Japanese characters" when language is not Japanese
  ext/css/settings.css
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1245 [ja] Add deinflection rule for 〜過ぎる
  benches/japanese-language-transformer.bench.js
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1251 Remove disambiguation prefix and suffix from css
  ext/css/display.css
Labels: kind/enhancement, area/ui-ux

#1252 Add option for scan without mouse move
  ext/data/schemas/options-schema.json
  ext/js/app/frontend.js
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/language/text-scanner.js
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#1228 [tl] Add tagalog deinflections
  .eslintrc.json
  ext/js/language/language-descriptors.js
  ext/js/language/tl/tagalog-transforms.js
  test/language/tagalog-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1260 [ja] add -nnee deinflection
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1254 [ko] Remove duplicated transforms rule
  ext/js/language/ko/korean-transforms.js
  test/language/korean-transforms.test.js
Labels: kind/bug, area/linguistics

#1263 [ja] add more n-slang deinflections
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1248 Add Stats in Dictionary Details
  ext/js/pages/settings/dictionary-controller.js
  ext/templates-settings.html
Labels: kind/enhancement, area/ui-ux

#1272 Only contain overscroll in popup
  ext/css/display.css
  ext/popup.html
Labels: kind/bug, area/ui-ux

#1278 Fix note generator audio
  ext/js/background/backend.js
  ext/js/pages/settings/anki-deck-generator-controller.js
Labels: kind/bug, area/anki, area/audio

#1281 Move search parser option under settings modal
  ext/css/search.css
  ext/search.html
Labels: kind/bug, area/ui-ux

#1279 [ja] deinflect -nya as -neba+ya
  ext/js/language/ja/japanese-transforms.js
  test/language/japanese-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1282 Add toggle for debug settings
  ext/css/settings.css
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/settings.html
  test/options-util.test.js
Labels: kind/enhancement, area/ui-ux

#991 Add recommended dictionaries to welcome page
  ext/data/recommended-dictionaries.json
  ext/data/schemas/recommended-dictionaries-schema.json
  ext/js/pages/settings/dictionary-import-controller.js
  ext/js/pages/welcome-main.js
  ext/templates-settings.html
  ext/welcome.html
  test/data/json.json
  types/ext/dictionary-recommended.d.ts
Labels: kind/enhancement, area/ui-ux

#1285 Expand "search non-Japanese characters" to Chinese and Cantonese
  ext/css/settings.css
  ext/js/language/translator.js
  ext/js/language/zh/chinese.js
  ext/settings.html
Labels: kind/enhancement

#1287 add cs, eo, lv, kn, uk
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1289 Update info.html
  ext/info.html
Labels: area/documentation
