Repository yomidevs/yomitan, pull requests merged in 2024-04, with the labels that each got.

#724 Simplify diacratic removal; modify Latin & Greek preprocessors
  .eslintrc.json
  ext/js/language/la/latin-text-preprocessors.js
  ext/js/language/language-descriptors.js
  ext/js/language/text-preprocessors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#773 feature: add handlebar for jidoujisho pitch graph
  ext/data/templates/anki-field-templates-upgrade-v29.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  ext/js/display/pronunciation-generator.js
  ext/js/templates/anki-template-renderer.js
  ext/settings.html
  test/options-util.test.js
Labels: kind/enhancement, area/anki

#785 Update docs for new add duplicate buttons
  docs/anki-integration.md
  ext/settings.html
  img/btn-add-duplicate-expression.png
  img/btn-add-duplicate-reading.png
Labels: area/documentation

#794 Rename language select options
  ext/js/pages/settings/languages-controller.js
Labels: kind/enhancement, area/ui-ux

#803 english grammar: adverb form of some adjectives
  ext/js/language/en/english-transforms.js
Labels: kind/enhancement, area/linguistics

#808 fix deinflection on past simple of english phrasal verbs
  ext/js/language/en/english-transforms.js
Labels: kind/bug, area/linguistics

#811 fix playwright failing on master
  ext/js/comm/anki-connect.js
  test/playwright/playwright-util.js
Labels: kind/bug

#791 Add scanOnTouchTap and improve touch scanning defaults
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/language/text-scanner.js
  ext/js/pages/settings/scan-inputs-controller.js
  ext/templates-settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#819 Fix tags not displaying for duplicate cards
  ext/js/background/backend.js
Labels: kind/bug

#806 improve term sorting
  ext/js/language/translator.js
  test/data/translator-test-results.json
  types/ext/dictionary.d.ts
Labels: kind/enhancement, area/ui-ux

#831 Added Old Irish
  .eslintrc.json
  ext/js/language/language-descriptors.js
  ext/js/language/sga/old-irish-transforms.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#829 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/documentation

#776 cache clipboard image to prevent duplicating in anki media
  ext/js/background/backend.js
Labels: kind/enhancement, area/anki

#784 abstract deinflection tests
  test/fixtures/language-transformer-test.js
  test/language-transformer.test.js
  test/language/english-transforms.test.js
  test/language/japanese-transforms.test.js
  types/test/language-transformer-test.ts
Labels: kind/meta, area/linguistics

#839 Fix search header left margins on small screens
  ext/css/search.css
Labels: kind/bug, area/ui-ux

#837 Change hotkey triggering condition to account for IME usage
  ext/js/input/hotkey-handler.js
Labels: kind/bug, area/ui-ux

#843 Prevent logging error when anki is disconnected
  ext/js/display/display-anki.js
Labels: kind/bug, area/anki

#848 start using german deinflections
  .eslintrc.json
  ext/js/language/language-descriptors.js
Labels: kind/enhancement, area/linguistics

#850 Bump webext-buildtools-firefox-sign-xpi-action to 1.0.8
  .github/workflows/publish-firefox-development.yml
Labels: area/dependencies, dependencies

#793 rework text processors
  .eslintrc.json
  ext/js/general/regex-util.js
  ext/js/general/text-source-map.js
  ext/js/language/ar/arabic-text-preprocessors.js
  ext/js/language/ja/japanese-text-preprocessors.js
  ext/js/language/ja/japanese-wanakana.js
  ext/js/language/ja/japanese.js
  ext/js/language/language-descriptors.js
  ext/js/language/languages.js
  ext/js/language/ru/russian-text-preprocessors.js
  ext/js/language/text-processors.js
  ext/js/language/translator.js
  test/data/anki-note-builder-test-results.json
  test/data/translator-test-inputs.json
  test/data/translator-test-results-note-data1.json
  test/data/translator-test-results.json
  test/japanese-util.test.js
  test/text-source-map.test.js
  types/ext/language-descriptors.d.ts
  types/ext/language.d.ts
  types/ext/translation-internal.d.ts
Labels: kind/meta, area/linguistics

#852 move Albanian grammar comments to test
  ext/js/language/sq/albanian-transforms.js
  test/language/albanian-transforms.test.js
Labels: kind/meta, area/linguistics

#853 add duplicate behavior dropdown
  docs/anki-integration.md
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display-anki.js
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux

#832 add profile switching keyboard shortcuts
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/pages/settings/keyboard-shortcuts-controller.js
  ext/templates-settings.html
  test/options-util.test.js
Labels: kind/enhancement, area/ui-ux

#862 Add option to disable furigana and reading in Term display style
  ext/css/display.css
  ext/data/schemas/options-schema.json
  ext/settings.html
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux

#858 fix profile select on search page not updating
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#860 Add blue variants of the add duplicate buttons
  ext/images/add-duplicate-term-kana-blue.svg
  ext/images/add-duplicate-term-kanji-blue.svg
Labels: kind/enhancement, area/ui-ux
