Repository yomidevs/yomitan, pull requests merged in 2024-12, with the labels that each got.

#1635 [FR] add apostrophe preprocessor
  .eslintrc.json
  ext/js/language/fr/french-text-preprocessors.js
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/bug

#1616 Set up getFrequencyOrder for other languages
  ext/js/pages/settings/sort-frequency-dictionary-controller.js
Labels: kind/meta, area/linguistics

#1623 Added npm scripts to ease building & testing on android platforms
  dev/bin/build.js
  dev/data/manifest-variants.json
  docs/development/npm-scripts.md
  package.json
Labels: kind/meta, area/ci

#1644 Fix firefox not showing Frequency Count when clicking on freq dict tag
  ext/js/display/display-generator.js
Labels: kind/bug, browser/firefox, area/ui-ux

#1646 Fix search page textbox size not shrinking when clicking clear button
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux

#1645 Fix leaking memory due to not improper cleanup of references to detached nodes
  ext/js/display/display-anki.js
  ext/js/display/element-overflow-controller.js
Labels: kind/bug, area/performance

#1652 Change messaging to dictionary size
  ext/js/display/display-generator.js
Labels: kind/enhancement, area/ui-ux

#1654 Fix CSS selector for off
  ext/css/action-popup.css
Labels: kind/bug, area/ui-ux

#1660 Fix collapse dictionary not working
  ext/js/display/element-overflow-controller.js
Labels: kind/bug, area/ui-ux, regression

#1662 Move "Persistent storage" to advanced settings
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1661 Add a link to the search page in popup settings
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1665 add esperanto transforms
  .eslintrc.json
  ext/js/language/eo/esperanto-transforms.js
  ext/js/language/language-descriptors.js
  test/language/esperanto-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1668 Add French de-inflection
  .eslintrc.json
  ext/js/language/fr/french-transforms.js
  ext/js/language/language-descriptors.js
Labels: kind/enhancement, area/linguistics

#1671 Make dict moving faster and save scroll location
  ext/js/pages/settings/dictionary-controller.js
  ext/templates-modals.html
Labels: kind/enhancement, area/performance, area/ui-ux

#1676 Fix bad performance.mark names causing performance.measure to fail
  ext/js/display/display.js
Labels: kind/bug, area/performance, area/ui-ux, priority/high, regression

#1675 Fix constant error on firefox mobile from chrome.contextMenus
  ext/js/background/backend.js
Labels: kind/bug, browser/firefox, platform/android-only

#1677 Add safePerformance to guard against bad performance calls
  .eslintrc.json
  dev/bin/schema-validate.js
  dev/dictionary-validate.js
  ext/js/app/frontend.js
  ext/js/app/popup.js
  ext/js/comm/cross-frame-api.js
  ext/js/core/promise-animation-frame.js
  ext/js/core/safe-performance.js
  ext/js/dictionary/dictionary-database.js
  ext/js/display/display-generator.js
  ext/js/display/display.js
  ext/js/language/text-scanner.js
  ext/js/language/translator.js
Labels: kind/meta, area/tech-debt

#1685 Leave url field blank when creating cards from search page
  ext/js/data/anki-note-builder.js
Labels: kind/enhancement, area/anki

#1695 Fix border size on some structured content images
  ext/css/structured-content.css
  ext/data/structured-content-style.json
  test/data/anki-note-builder-test-results.json
Labels: kind/bug, area/ui-ux, regression

#1693 Add chrome dev crx to releases
  .github/workflows/publish-chrome-development.yml
Labels: area/ci

#1696 Fix image render area
  ext/js/display/structured-content-generator.js
  test/data/anki-note-builder-test-results.json
Labels: kind/bug, area/ui-ux, regression

#1697 Add upload_url to publish-chrome-development action
  .github/workflows/create-prerelease-on-tag.yml
  .github/workflows/publish-chrome-development.yml
Labels: area/ci

#1699 Fix svg styling and image scaling
  dev/data/structured-content-overrides.css
  ext/css/structured-content.css
  ext/data/structured-content-style.json
  ext/js/dictionary/dictionary-database.js
  ext/js/display/structured-content-generator.js
  test/data/anki-note-builder-test-results.json
  types/ext/dictionary-database.d.ts
Labels: kind/bug, area/ui-ux, regression

#1701 Avoid using `URL.canParse`
  ext/js/data/anki-note-builder.js
Labels: kind/bug, browser/kiwi

#1700 Mostly fix monochrome svg rendering color and styling
  dev/data/structured-content-overrides.css
  ext/css/structured-content.css
  ext/data/structured-content-style.json
  ext/js/display/structured-content-generator.js
  test/data/anki-note-builder-test-results.json
Labels: kind/bug, area/ui-ux, regression

#1705 Fix uncollapse link and clicking on images
  .eslintrc.json
  ext/css/display.css
  ext/css/structured-content.css
  ext/data/structured-content-style.json
  ext/js/display/display-content-manager.js
  ext/js/display/structured-content-generator.js
  test/data/anki-note-builder-test-results.json
Labels: kind/bug, area/ui-ux, regression

#1706 Add script for writing anki structured content css
  docs/development/npm-scripts.md
  package.json
Labels: kind/meta

#1708 Add actionlint & fix detected issues
  .github/actionlint-matcher.json
  .github/workflows/actionlint.yml
  .github/workflows/auto-approve.yml
  .github/workflows/create-prerelease-on-tag.yml
  .github/workflows/delay.yml
  .github/workflows/playwright_comment.yml
  .github/workflows/publish-chrome-development.yml
  .github/workflows/publish-chrome.yml
  test/data/json.json
Labels: kind/meta, area/ci

#1710 Update dependencies
  package-lock.json
  package.json
  playwright.config.js
Labels: area/dependencies

#1712 eslint 9 & misc dependency updates
  .eslintignore
  .eslintrc.json
  .htmlvalidate.json
  .husky/pre-commit
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  CONTRIBUTING.md
  dev/jsconfig.json
  eslint.config.js
  ext/js/background/backend.js
  ext/js/data/options-util.js
  ext/js/dictionary/dictionary-database.js
  ext/js/pages/permissions-main.js
  ext/js/pages/settings/dictionary-controller.js
  ext/js/pages/settings/profile-controller.js
  ext/js/pages/settings/recommended-settings-controller.js
  package-lock.json
  package.json
  test/data/json.json
  test/eslint-config.test.js
Labels: kind/meta, area/dependencies, area/ci

#1713 Update all remaining devDependencies
  package-lock.json
  package.json
Labels: kind/meta, area/dependencies

#1716 Speed up CI by parallelizing more things
  .github/actions/setup/action.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/create-prerelease-on-tag.yml
  .github/workflows/playwright.yml
  package.json
Labels: kind/meta, area/ci

#1717 Speed up playwright (pt1: preparation)
  test/data/database-test-cases.json
  test/data/dictionaries/valid-dictionary1/term_bank_1.json
  test/data/html/js/popup-tests.js
  test/data/html/popup-tests.html
  test/playwright/visual.spec.js
Labels: kind/meta, area/ci

#1718 Fix broken dictionary collection import
  ext/js/dictionary/dictionary-database.js
  test/utilities/database.js
Labels: kind/bug, regression

#1719 skip bench on merge_group as it's not supported
  .github/workflows/ci.yml
Labels: kind/meta, area/ci

#1722 Sanitize css before sending to Anki
  ext/js/core/utilities.js
  ext/js/data/anki-note-builder.js
Labels: kind/bug, area/anki

#1567 Add Yiddish support to Yomitan
  ext/js/language/language-descriptors.js
  ext/js/language/yi/yiddish-text-postprocessors.js
  ext/js/language/yi/yiddish-text-preprocessors.js
  ext/js/language/yi/yiddish-transforms.js
  test/language/yiddish-transforms.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1724 [et] Add Estonian
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement

#1720 Speed up playwright (pt2: full parallelization)
  .github/workflows/playwright.yml
  .github/workflows/playwright_comment.yml
  playwright.config.js
  test/playwright/visual.spec.js
Labels: kind/meta, area/ci
