Repository yomidevs/yomitan, pull requests merged in 2025-09, with the labels that each got.

#2149 Clarify usage of Flags type in Profile Conditions
  ext/templates-modals.html
Labels: kind/enhancement, area/ui-ux

#2129 Remove separate handling for avg freq in popup and combine with Anki handling
  ext/js/data/anki-note-data-creator.js
  ext/js/dictionary/dictionary-data-util.js
  types/ext/dictionary.d.ts
Labels: kind/bug, area/ui-ux

#2164 Improve mouse input action prevention
  ext/data/schemas/options-schema.json
  ext/js/app/frontend.js
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/language/text-scanner.js
  ext/templates-modals.html
  test/options-util.test.js
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux, area/settings

#2167 Fix anki flashcard format errors on deleting too many
  ext/js/pages/settings/anki-controller.js
Labels: kind/bug, area/anki

#2175 Add "Reduced motion scrolling" option
  ext/data/schemas/options-schema.json
  ext/js/display/display.js
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux, area/settings

#2173 Fixing the logic in isNonNounVerbOrAdjective
  ext/js/dictionary/dictionary-data-util.js
Labels: kind/enhancement, area/linguistics

#2179 [el] Add processor to support double acute-accented words
  ext/js/language/el/modern-greek-processors.js
  ext/js/language/language-descriptors.js
  test/language/modern-greek-processors.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics
