Repository yomidevs/yomitan, pull requests merged in 2025-05, with the labels that each got.

#1973 fix playwright anki-add test
  ext/js/background/backend.js
  test/playwright/integration.spec.js
Labels: kind/meta, area/ci

#1979 Remove ending slash from ankiconnect ignore
  .lycheeignore
Labels: kind/meta, area/ci

#1978 Change view notes button color based on card state
  ext/css/display.css
  ext/images/view-note-buried.svg
  ext/images/view-note-learning.svg
  ext/images/view-note-review.svg
  ext/images/view-note-suspended.svg
  ext/js/comm/anki-connect.js
  ext/js/display/display-anki.js
  types/ext/anki.d.ts
Labels: kind/enhancement, area/ui-ux, area/anki

#1974 Recommended setting to disable single quotes as sentence terminators
  ext/data/recommended-settings.json
Labels: kind/enhancement, area/settings

#1852 Fix images breaking on Firefox after a while (add heartbeat to prevent background page reap)
  ext/js/application.js
  ext/js/background/backend.js
  ext/js/background/offscreen.js
  ext/js/comm/api.js
  ext/js/comm/shared-worker-bridge.js
  ext/js/dictionary/dictionary-database-worker-handler.js
  ext/js/dictionary/dictionary-database.js
  ext/js/display/media-drawing-worker.js
  types/ext/api.d.ts
Labels: kind/bug, area/performance

#1985 Improve Spanish transforms
  ext/js/language/es/spanish-transforms.js
Labels: kind/enhancement, area/linguistics

#1982 Return array filled with false in canAddNotes if Anki is disabled
  ext/js/comm/anki-connect.js
Labels: kind/bug, area/anki

#1984 Hide progress and error containers for import/export dictionary collection until used
  ext/css/settings.css
  ext/js/pages/settings/backup-controller.js
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1981 Add option to reset settings of individual profiles
  ext/js/pages/settings/profile-controller.js
  ext/templates-modals.html
  ext/templates-settings.html
Labels: kind/enhancement, area/ui-ux, area/settings

#1998 Move omnibox init to _prepareInternal to avoid chance of duplicating
  ext/js/background/backend.js
Labels: kind/bug

#1963 Quick start overhaul
  ext/css/settings.css
  ext/images/browser-action-popup.webp
  ext/images/scanning-popup.webp
  ext/images/settings-dictionaries-popup.webp
  ext/info.html
  ext/quick-start-guide.html
  ext/welcome.html
  resources/images/browser-action-popup.webp
Labels: area/documentation, kind/enhancement, area/ui-ux

#1992 Add Spanish stem-changing verbs deinflection
  ext/js/language/es/spanish-transforms.js
  test/language/spanish-transforms.test.js
Labels: kind/enhancement, area/linguistics

#1997 Allow selecting different flashcard formats in note generator
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/templates-modals.html
  types/ext/settings.d.ts
Labels: kind/enhancement, area/anki

#2002 Disable Anki add button if dupe check is disabled and note is invalid
  ext/js/data/anki-util.js
  ext/js/display/display-anki.js
Labels: kind/enhancement, area/anki

#2011 Recommend resetting scanning.scanResolution and translation.searchResolution for ja, zh, yue
  ext/data/recommended-settings.json
Labels: kind/bug

#2008 [ja] Add preprocessor to convert kanji variants to standard form
  dev/lib/kanji-processor.js
  ext/js/language/ja/japanese-text-preprocessors.js
  ext/js/language/language-descriptors.js
  package-lock.json
  package.json
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1983 Combine `Default profile` and `Editing profile` options into `Active profile`
  ext/js/pages/settings/profile-controller.js
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#2029 Fix `scan-disable` being bypassed for some elements
  ext/js/dom/text-source-element.js
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#2027 Fix disabled scanning on search page not disabling for touch
  ext/js/display/display.js
  ext/js/display/query-parser.js
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux, area/tech-debt
