Repository yomidevs/yomitan, pull requests merged in 2025-02, with the labels that each got.

#1802 Bump awalsh128/cache-apt-pkgs-action to version that does not use deprecated dependencies
  .github/workflows/playwright.yml
Labels: area/ci

#1811 Only show dictionaries with at least one term for single-glossary handlebars
  ext/js/data/anki-template-util.js
  ext/js/display/display-anki.js
  ext/js/pages/settings/anki-controller.js
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/js/pages/settings/anki-templates-controller.js
  ext/js/pages/settings/settings-main.js
Labels: kind/bug, area/ui-ux

#1809 Use addScopeToCssLegacy to fix dict css on Kiwi due to out of date Chromium base
  ext/js/display/display.js
Labels: kind/bug, area/ui-ux

#1810 Make anki error footer notification text red and bold
  ext/css/display.css
Labels: kind/enhancement, area/ui-ux

#1546 Replace Audio Error Click Sound
  .lycheeignore
  README.md
  ext/data/audio/button.mp3
Labels: kind/enhancement, area/ui-ux

#1687 Add docs on commit signing
  CONTRIBUTING.md
Labels: area/documentation

#1791 More spanish transforms
  docs/development/language-features.md
  ext/js/language/es/spanish-transforms.js
  test/language/spanish-transforms.test.js
  types/ext/language-transformer.d.ts
Labels: area/documentation, kind/enhancement, area/linguistics

#1799 profile name shown on action bar
  ext/css/display.css
  ext/js/display/display-profile-selection.js
  ext/popup.html
Labels: kind/enhancement, area/ui-ux

#1826 Allow disabling audio fallback sound
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display-audio.js
  ext/js/media/audio-system.js
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux, area/audio

#1825 add overwriting options to each field
  ext/css/settings.css
  ext/data/schemas/options-schema.json
  ext/js/data/anki-note-builder.js
  ext/js/data/options-util.js
  ext/js/data/permissions-util.js
  ext/js/display/display-anki.js
  ext/js/pages/settings/anki-controller.js
  ext/js/pages/settings/anki-templates-controller.js
  ext/settings.html
  ext/templates-modals.html
  ext/templates-settings.html
  test/options-util.test.js
  test/playwright/integration.spec.js
  test/utilities/anki.js
  types/ext/anki-note-builder.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/anki

#1815 Fix cutoff indicator and audio failed X on search page
  ext/css/display.css
  ext/css/search.css
Labels: kind/bug, area/ui-ux, regression

#1839 Add option to select type of fallback sound
  README.md
  ext/data/audio/fallback-bloop.mp3
  ext/data/audio/fallback-click.mp3
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display-audio.js
  ext/js/media/audio-system.js
  ext/settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux

#1822 Add support for omnibox search with Yomitan
  dev/data/manifest-variants.json
  ext/js/background/backend.js
Labels: kind/enhancement, area/ui-ux

#1834 Add {sentence-furigana-plain} handlebar
  ext/data/templates/anki-field-templates-upgrade-v61.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/anki-note-builder.js
  ext/js/data/anki-template-util.js
  ext/js/data/options-util.js
  ext/js/templates/template-renderer-media-provider.js
  ext/templates-modals.html
  test/data/anki-note-builder-test-results.json
  test/options-util.test.js
  types/ext/anki-note-builder.d.ts
  types/ext/anki-templates.d.ts
Labels: kind/enhancement, area/anki

#1479 add average frequency tag
  ext/css/display.css
  ext/data/schemas/options-schema.json
  ext/js/dictionary/dictionary-data-util.js
  ext/js/display/display.js
  ext/settings.html
  test/options-util.test.js
  types/ext/dictionary.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/ui-ux

#1818 [grc] basic deinflection
  ext/js/language/grc/ancient-greek-processors.js
  ext/js/language/grc/ancient-greek-transforms.js
  ext/js/language/language-descriptors.js
  test/language/ancient-greek-processors.test.js
  test/language/ancient-greek-transforms.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1841 Normalize fallback-bloop.mp3 audio
  ext/data/audio/fallback-bloop.mp3
Labels: kind/enhancement, area/ui-ux
