Repository yomidevs/yomitan, pull requests merged in 2025-07, with the labels that each got.

#2078 Add privacy policy file
  PRIVACY-POLICY.md
Labels: area/documentation

#2073 Georgian language support
  ext/js/language/ka/georgian-transforms.js
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#2077 Update kaikki link in recommended dictionaries
  ext/templates-modals.html
Labels: kind/enhancement

#2076 Re-inflate newlines in media for Anki when rendering templates
  ext/js/templates/template-renderer-media-provider.js
Labels: kind/enhancement, area/anki

#2082 search: fix IME composition commit triggering search
  ext/js/display/search-display-controller.js
Labels: kind/bug

#2084 Update settings page settings when profile is switched using action popup
  ext/js/pages/settings/profile-controller.js
Labels: kind/bug, area/ui-ux, regression

#2081 Note potential data being sent on settings and add audio toggle to welcome page
  PRIVACY-POLICY.md
  ext/settings.html
  ext/welcome.html
Labels: area/documentation, browser/firefox

#2080 Add options to parse and dedupe input for the Anki Note Generator
  ext/css/settings.css
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/templates-modals.html
Labels: kind/enhancement, area/ui-ux, area/anki

#2085 Add media support to Yomitan API
  ext/js/background/backend.js
  ext/js/comm/yomitan-api.js
  ext/js/core/utilities.js
  ext/js/data/anki-note-builder.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/anki-util.js
  ext/js/display/display.js
  ext/js/pages/settings/anki-deck-generator-controller.js
  types/ext/yomitan-api.d.ts
Labels: kind/enhancement, area/api

#2103 Preserve uppercase when converting romaji to katakana using uppercase romaji
  ext/js/language/ja/japanese-wanakana.js
  test/japanese-util.test.js
Labels: kind/bug

#2102 Make getLanguageFromText more accurate and mostly avoid conflict with Japanese, Chinese, Cantonese
  ext/js/display/display-generator.js
  ext/js/display/structured-content-generator.js
  ext/js/language/text-utilities.js
Labels: kind/bug, area/ui-ux

#2100 Change default Yomitan API port to 19633
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/settings.html
  test/options-util.test.js
Labels: area/api, area/ui-ux
