Repository yomidevs/yomitan, pull requests merged in 2025-03, with the labels that each got.

#1849 add modern Irish option
  ext/js/language/ga/irish-transforms.js
  ext/js/language/language-descriptors.js
  test/language/irish-transforms.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1844 add overwrite option to prefer new value
  ext/data/schemas/options-schema.json
  ext/js/display/display-anki.js
  ext/templates-settings.html
  types/ext/settings.d.ts
Labels: kind/enhancement, area/anki

#1854 make russian preprocessor bidirectional
  ext/js/language/ru/russian-text-preprocessors.js
  types/ext/language-descriptors.d.ts
Labels: area/linguistics

#1853 Set scanOnPenHover to false by default
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/pages/settings/scan-inputs-controller.js
  test/options-util.test.js
Labels: kind/enhancement, area/ui-ux

#1863 move overwriting warning to more-toggle
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1845 Pierce shadowroots on Chromium using caretPositionFromPoint
  ext/js/dom/text-source-generator.js
Labels: kind/enhancement, browser/chrome, browser/edge

#1869 Improve default anki field setup
  ext/js/pages/settings/anki-controller.js
Labels: kind/enhancement, area/ui-ux, area/anki

#1848 Fix finding media to inject in anki note generator
  ext/js/pages/settings/anki-deck-generator-controller.js
Labels: kind/bug, area/anki

#1872 Remove expected fail from playwright shadow dom open label
  test/data/html/popup-tests.html
Labels: kind/meta, area/ci

#1875 Fix wanakana breaking IME input when hitting a conversion containing latin characters
  ext/js/display/search-display-controller.js
  ext/js/language/ja/japanese-wanakana.js
  ext/js/pages/settings/popup-preview-frame.js
Labels: kind/bug, area/ui-ux

#1880 Allow ordering audio sources
  ext/css/settings.css
  ext/js/pages/settings/audio-controller.js
  ext/templates-modals.html
  ext/templates-settings.html
Labels: kind/enhancement, area/ui-ux

#1891 Fall back to `caretRangeFromPoint` more aggressively to save Kiwi from being unable to scan
  ext/js/dom/text-source-generator.js
Labels: kind/bug, priority/high, regression

#1881 make phonetic transcriptions handlebar css-selectable
  ext/data/templates/anki-field-templates-upgrade-v63.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/js/data/options-util.js
  test/data/anki-note-builder-test-results.json
  test/options-util.test.js
Labels: kind/enhancement, area/anki

#1895 Add visibility-modifiers.css to welcome page
  ext/welcome.html
Labels: kind/bug, area/ui-ux

#1893 Add 'language' parameter to audio API call
  ext/js/media/audio-downloader.js
Labels: kind/enhancement, area/audio

#1886 Remove profile selector from search page if user has only one profile
  ext/js/display/search-display-controller.js
Labels: kind/enhancement, area/ui-ux

#1885 Add horizontal padding to search header
  ext/css/search.css
Labels: kind/bug, area/ui-ux, regression

#1897 Add missing termMeta to dict details modal
  ext/js/pages/settings/dictionary-controller.js
Labels: kind/bug, area/ui-ux

#1898 Detect missing entries when dicts fail to import with `Check Integrity` button
  ext/css/settings.css
  ext/js/pages/settings/dictionary-controller.js
  ext/templates-modals.html
  ext/templates-settings.html
Labels: kind/bug, area/ui-ux

#1900 Make wording of clipboard related things language agnostic
  ext/permissions.html
  ext/settings.html
Labels: kind/enhancement, area/ui-ux

#1899 Use normal anchor hashes in anchor links
  ext/issues.html
  ext/js/pages/settings/settings-display-controller.js
  ext/popup.html
  ext/quick-start-guide.html
  ext/search.html
  ext/settings.html
  ext/templates-display.html
Labels: kind/bug, area/ui-ux

#1901 Don't clear existing search when clipboard is updated and `Update query only` is set
  ext/js/display/display.js
Labels: kind/enhancement, area/ui-ux

#1905 Move updateAliasSettings out of private functions area
  ext/js/pages/settings/dictionary-controller.js
Labels: kind/meta

#1902 Pull update url from existing entries when moving to prevent update button from appearing when it shouldnt
  ext/js/pages/settings/dictionary-controller.js
Labels: kind/bug, area/ui-ux, regression

#1903 Preserve integrity check details when moving around dictionaries
  ext/js/pages/settings/dictionary-controller.js
Labels: kind/enhancement, area/ui-ux

#1910 Replace wanakana
  README.md
  benches/jsconfig.json
  dev/lib/wanakana.js
  ext/js/display/search-display-controller.js
  ext/js/language/ja/japanese-kana-romaji-dicts.js
  ext/js/language/ja/japanese-wanakana.js
  ext/js/pages/settings/popup-preview-frame.js
  ext/legal-npm.html
  jsconfig.json
  package-lock.json
  package.json
  test/japanese-util.test.js
  test/jsconfig.json
  types/ext/language.d.ts
Labels: kind/meta, area/dependencies, area/tech-debt

#1915 Add symbols support to romaji and kana processing
  ext/js/language/ja/japanese-kana-romaji-dicts.js
Labels: kind/bug

#1914 Update user facing dependencies
  eslint.config.js
  ext/js/pages/settings/backup-controller.js
  package-lock.json
  package.json
  test/language-transformer-cycles.test.js
Labels: area/dependencies, dependencies

#1918 Fix underline on kanji headword characters jumping around with different fonts
  ext/css/display.css
Labels: kind/enhancement, area/ui-ux
