Repository yomidevs/yomitan, pull requests merged in 2025-04, with the labels that each got.

#1925 Turn off autocapitalize on search textarea
  ext/search.html
Labels: kind/enhancement, area/ui-ux

#1933 hide ja-specific handlebars for other languages
  ext/js/data/anki-template-util.js
  ext/js/pages/settings/anki-controller.js
Labels: kind/enhancement, area/ui-ux

#1936 Partially preserve newlines in search queries on search page
  ext/js/data/string-util.js
  ext/js/display/query-parser.js
Labels: kind/enhancement, area/ui-ux

#1939 Check if modifier is set when scanning from keypress without move before pushing through synthetic mouse event
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#1944 Fix handling of n' in romaji to kana
  ext/js/language/ja/japanese-kana-romaji-dicts.js
Labels: kind/bug, area/ui-ux, regression

#1947 Cut out unnecessary fields when dupe checking to reduce AnkiConnect network latency
  ext/js/background/backend.js
Labels: kind/enhancement, area/performance, area/anki

#1949 Fix ny becoming んy
  ext/js/language/ja/japanese-wanakana.js
  test/japanese-util.test.js
Labels: kind/bug, area/ui-ux, regression

#1950 Update search query text when searching and set cursor to end of line
  ext/js/display/search-display-controller.js
Labels: kind/enhancement, area/ui-ux

#1951 Add jmnedict to recommended dictionaries for japanese
  ext/data/recommended-dictionaries.json
Labels: kind/enhancement

#1926 Handle mobile browsers pretending to be composing
  ext/js/display/display.js
  ext/js/display/search-display-controller.js
  ext/js/language/ime-utilities.js
  ext/js/pages/settings/popup-preview-frame.js
Labels: kind/bug, platform/android-only

#1958 Add Arabic language transforms
  ext/data/recommended-dictionaries.json
  ext/data/recommended-settings.json
  ext/js/language/ar/arabic-text-preprocessors.js
  ext/js/language/ar/arabic-transforms.js
  ext/js/language/language-descriptors.js
  test/language/arabic-transforms.test.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1966 Check for wanakanaEnabled on search page before applying kana conversion
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/ui-ux, priority/high, regression

#1967 [id] add removeDiacritics preprocessor
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1968 Prevent search page profile changing duplicating event listeners every time profile is switched
  ext/js/display/search-display-controller.js
Labels: kind/bug, area/performance

#1930 allow multiple anki note loadouts
  ext/css/display.css
  ext/css/settings.css
  ext/data/schemas/options-schema.json
  ext/data/templates/anki-field-templates-upgrade-v64.handlebars
  ext/data/templates/default-anki-field-templates.handlebars
  ext/images/add-duplicate-big-circle-blue.svg
  ext/images/add-duplicate-big-circle.svg
  ext/images/add-duplicate-big-diamond.svg
  ext/images/add-duplicate-big-square.svg
  ext/images/add-duplicate-small-circle-blue.svg
  ext/images/add-duplicate-small-circle.svg
  ext/images/big-circle.svg
  ext/images/big-diamond.svg
  ext/images/big-square.svg
  ext/images/overwrite-big-circle.svg
  ext/images/overwrite-big-diamond.svg
  ext/images/overwrite-big-square.svg
  ext/images/overwrite-small-circle.svg
  ext/images/small-circle.svg
  ext/js/data/anki-note-builder.js
  ext/js/data/anki-note-data-creator.js
  ext/js/data/options-util.js
  ext/js/data/permissions-util.js
  ext/js/display/display-anki.js
  ext/js/pages/settings/anki-controller.js
  ext/js/pages/settings/anki-deck-generator-controller.js
  ext/js/pages/settings/anki-templates-controller.js
  ext/js/pages/settings/dictionary-import-controller.js
  ext/js/pages/settings/keyboard-shortcuts-controller.js
  ext/js/pages/settings/settings-main.js
  ext/settings.html
  ext/templates-display.html
  ext/templates-modals.html
  ext/templates-settings.html
  test/anki-template-renderer.test.js
  test/data/translator-test-results-note-data1.json
  test/options-util.test.js
  test/playwright/integration.spec.js
  test/utilities/anki.js
  types/ext/anki-note-builder.d.ts
  types/ext/anki-templates-internal.d.ts
  types/ext/anki-templates.d.ts
  types/ext/display-anki.d.ts
  types/ext/settings.d.ts
Labels: kind/enhancement, area/anki

#1972 Add foosoft ankiconnect repo to lycheeignore
  .lycheeignore
Labels: kind/meta

#1874 Add compact gloss css to dictionaries when exporting to anki
  dev/data/structured-content-overrides.css
  ext/css/display.css
  ext/css/structured-content.css
  ext/data/anki-compact-gloss-style.js
  ext/data/schemas/options-schema.json
  ext/data/structured-content-style.json
  ext/js/data/anki-note-data-creator.js
  ext/settings.html
  types/ext/settings.d.ts
Labels: kind/bug, area/anki
