Repository yomidevs/yomitan, pull requests merged in 2025-01, with the labels that each got.

#1726 Fix css scope adder function
  ext/js/core/utilities.js
  ext/js/data/anki-note-data-creator.js
  ext/js/display/display.js
  test/data/anki-note-builder-test-results.json
  test/data/translator-test-results-note-data1.json
Labels: kind/bug, area/ui-ux, area/anki

#1727 Fix playwright
  .github/workflows/playwright.yml
  .github/workflows/playwright_comment.yml
Labels: kind/meta, area/ci

#1728 Really fix playwright
  .github/workflows/playwright.yml
Labels: kind/meta, area/ci

#1733 Really fix playwright fr finally
  .github/workflows/playwright.yml
  .github/workflows/playwright_comment.yml
Labels: kind/meta, area/ci

#1735 Fix flaky Anki playwright test
  test/playwright/integration.spec.js
Labels: kind/meta, area/ci

#1729 Update to node 22
  package-lock.json
  package.json
  shell.nix
Labels: kind/meta, area/dependencies, area/ci

#1734 More minor playwright performance improvements
  test/playwright/visual.spec.js
Labels: kind/meta, area/ci

#1738 Add back content-visibility: auto and make image go upwards to not get cut off when on bottom of entry container
  ext/css/display.css
  ext/css/structured-content.css
  ext/data/structured-content-style.json
Labels: kind/enhancement, area/performance, area/ui-ux

#1742 Modify tag.sh to sign tags
  tag.sh
Labels: kind/meta, area/ci

#1741 Try and reduce playwright flakiness
  test/playwright/visual.spec.js
Labels: kind/meta, area/ci

#1743 Remove \r from anki note generator tsv
  ext/js/pages/settings/anki-deck-generator-controller.js
Labels: kind/bug, area/anki

#1747 Fix Anki css scoping breaking due to Anki shipping with incredibly out of date Chromium version (112)
  ext/js/core/utilities.js
  ext/js/data/anki-note-data-creator.js
Labels: kind/bug, area/anki, regression

#1749 [la] add preprocessor for ae and oe diphthongs
  ext/js/language/la/latin-text-preprocessors.js
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1764 Add minimumTouchTime setting to scanning inputs settings
  ext/data/schemas/options-schema.json
  ext/js/data/options-util.js
  ext/js/display/display.js
  ext/js/language/text-scanner.js
  ext/js/pages/settings/scan-inputs-controller.js
  ext/templates-settings.html
  test/options-util.test.js
  types/ext/settings.d.ts
  types/ext/text-scanner.d.ts
Labels: kind/enhancement, area/ui-ux

#1750 Allow dictionaries to specify minimum compatible Yomitan version
  ext/data/schemas/dictionary-index-schema.json
  ext/js/dictionary/dictionary-importer.js
  ext/js/pages/settings/dictionary-import-controller.js
  test/database.test.js
  test/fixtures/translator-test.js
  types/ext/dictionary-data.d.ts
  types/ext/dictionary-importer.d.ts
Labels: kind/enhancement, area/dictionary-format

#1763 Add Welsh support
  ext/js/language/language-descriptors.js
  types/ext/language-descriptors.d.ts
Labels: kind/enhancement, area/linguistics

#1773 Update dictionary will update dictionary CSS
  ext/js/pages/settings/dictionary-import-controller.js
Labels: kind/bug

#1777 Apply preventNextMouseDown for touch end to prevent instantly closing popup
  ext/js/language/text-scanner.js
Labels: kind/bug, area/ui-ux

#1782 Fix setStartOffset stopAtWordBoundary behavior to terminate at the beginning of current div
  ext/js/dom/dom-text-scanner.js
  test/data/html/dom-text-scanner.html
Labels: kind/bug, area/anki
